describe('Home page testing', () => {
    it('shoud open home page', () => {
        cy.visit('/')
        cy.get('h1').should('contain', 'Modsen Currency')
    })
    it('change theme', () => {
        cy.visit('/')
        cy.get('label[for=themeSwitcher]').click()
        cy.get('label[for=themeSwitcher]>*:nth-child(2)').should('have.css', 'border', '1.6px solid rgb(3, 3, 4)')
        cy.get('label[for=themeSwitcher]').click()
        cy.get('label[for=themeSwitcher]>*:nth-child(2)').should('have.css', 'border', '1.6px solid rgb(255, 255, 255)')
    })
    it('click to header nav', () => {
        cy.visit('/')
        cy.contains('Timeline').click()
        cy.url().should('include', '/timeline')
        cy.contains('Bank').click()
        cy.url().should('include', '/bank')
        cy.contains('Contacts').click()
        cy.url().should('include', '/contacts')
    })
    it('open popup on firt element, type and convert value', () => {
        cy.visit('/')
        cy.get('[data-cy="currency-card"]:first-child').click({ multiple: true })
        cy.get('[data-cy="popup"]').should('have.css', 'pointer-events', 'all')
        cy.contains('Argentine Peso')
        cy.get('[data-cy="popup"]').find('input').first().type(123)
        cy.get('[data-cy="popup"]').find('input').last().should('have.value', '0.13')
        cy.get('[data-cy="dropdown"]').click()
        cy.get('[data-cy="dropdown"]').find('li:nth-child(5)').click()
        cy.get('[data-cy="dropdown"]').contains('CNY')
        cy.get('[data-cy="popup"]').find('input').last().should('have.value', '0.96')
        cy.get('[data-cy="popup-close"]').click()
        cy.get('[data-cy="popup"]').should('have.css', 'pointer-events', 'none')
    })
    it('get on notFound page and get back to home', () => {
        cy.visit('/')
        cy.contains('Market').click()
        cy.contains('404')
        cy.contains('Click here').click()
        cy.url().should('include', '/')
    })
})
